# For more information: https://laravel.com/docs/sail
version: '3.3'
services:
    laravel:
        image: bitnami/laravel
        restart: always
        container_name: ${SERVERNAME}_laravel
        environment:
            DB_HOST: mysql
            DB_USERNAME: ${DB_USERNAME}
            DB_DATABASE: ${DB_DATABASE}
            DB_PASSWORD: ${DB_PASSWORD}
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            VIRTUAL_PORT: 3000
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            TZ: ${TIMEZONE}
        expose:
            - 3000
        volumes:
            - ./:/app
        networks:
            - nginx-proxy
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - selenium
        privileged: true
    mysql:
        image: mysql
        container_name: ${SERVERNAME}_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            TZ: ${TIMEZONE}
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: ${SERVERNAME}_redis
        restart: always
        # ports:
        #     - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: ${SERVERNAME}_meilisearch
        restart: always
        # ports:
        #     - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
          retries: 3
          timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        container_name: ${SERVERNAME}_mailhog
        restart: always
        # ports:
        #     - '${FORWARD_MAILHOG_PORT:-1025}:1025'
        #     - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
        image: 'selenium/standalone-chrome'
        container_name: ${SERVERNAME}_selenium
        restart: always
        volumes:
              - '/dev/shm:/dev/shm'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${SERVERNAME}_phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            # PMA_ARBITRARY: 1
            VIRTUAL_HOST: ${VIRTUAL_HOST_DB_PREFIX}.${VIRTUAL_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${VIRTUAL_HOST_DB_PREFIX}.${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            TZ: ${TIMEZONE}
        restart: always
        expose:
            - 80
        networks:
            - nginx-proxy
            - sail

volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local

networks:
    sail:
        driver: bridge
    nginx-proxy:
        external:
            name: nginx-proxy