name: 'ShellCheck: Error checking for shell scripts'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
